[global]
namespace = "quad"
frozen = false
license = '''
The MIT License (MIT)
Copyright (c) 2023 Kevin Walchko
see LICENSE for full details
'''

[global.serialize]
yivo = true
mavlink = false

[global.ids]
heartbeat = 20
imu_raw_t = 40
imu_t = 41
calibration_t = 40