[global]
namespace = "quad"
frozen = false
license = '''
The MIT License (MIT)
Copyright (c) 2023 Kevin Walchko
see LICENSE for full details
'''

[global.serialize]
yivo = true
mavlink = false

[global.ids]

imu_t = 20
calibration_t = 21