[message]
accel = {type = "uint16", len=3, default = [0,0,0]}
gyro = {type = "uint16", len=3, default = [0,0,0]}
mag = {type = "uint16", len=3, default = [0,0,0]}
imu_temperature = "uint16"
pressure = "float"
temperature = "float"
timestamp = "uint32"

# vec-accel = 1
# vec-gyro = 1
# vec-mag = 1
# float-imu_temperature = 1
# float-pressure = 1
# uint16-temperature = 1
# uint32-timestamp = 1

name = "imu_raw_t"