
[enums.sensor]
none = 0
accels = 1
gyros = 2
mags = 4
pressure = 8
temperature = 16

[message]
vec_t-accel = [0,0,0]
vec_t-gyro = [0,0,0]
vec_t-mag = [0,0,0]
float-imu_temperature = 0
float-pressure = 0
float-temperature = 0
uint32-timestamp = 0
name = "imu_t"
